CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" int NOT NULL,
  "email" varchar(35) UNIQUE NOT NULL,
  "password" varchar(15) UNIQUE NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" int NOT NULL,
  "description" varchar(50) NOT NULL,
  "level" varchar(20) NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" int NOT NULL,
  "url" varchar
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25)
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "users_role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL,
  "role" int NOT NULL
);

CREATE TABLE "courses_category" (
  "id" int PRIMARY KEY NOT NULL,
  "category" int NOT NULL,
  "title" varchar(40)
);

ALTER TABLE "course_video" ADD FOREIGN KEY ("title") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "users_role" ADD FOREIGN KEY ("role") REFERENCES "roles" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("name") REFERENCES "users_role" ("id");

ALTER TABLE "courses_category" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("title") REFERENCES "courses_category" ("id");

courses_exercise=# INSERT INTO roles (name) VALUES ('Mario'), ('Valeria'), ('Alex');
INSERT 0 3
courses_exercise=# INSERT INTO categories (name) VALUES ('Programming'), ('Finance'), ('Nutrition');
INSERT 0 3
courses_exercise=# SELECT * FROM roles;
 id |  name
----+---------
  1 | Mario
  2 | Valeria
  3 | Alex
(3 filas)


courses_exercise=# UPDATE roles SET name='Student' WHERE id=1;
UPDATE 1
courses_exercise=# UPDATE roles SET name='Teacher' WHERE id=2;
UPDATE 1
courses_exercise=# UPDATE roles SET name='Admin' WHERE id=3;
UPDATE 1
courses_exercise=# SELECT * FROM roles;
 id |  name
----+---------
  1 | Student
  2 | Teacher
  3 | Admin
(3 filas)


courses_exercise=# INSERT INTO users_role (name, role) VALUES ('Mario', 1), ('Valeria', 2), ('Alex', 3);
INSERT 0 3
courses_exercise=# SELECT * FROM categories;
 id |    name
----+-------------
  1 | Programming
  2 | Finance
  3 | Nutrition
(3 filas)


courses_exercise=# INSERT INTO courses_category (category, title) VALUES (1, 'CSS Flexbox'), (2, 'Finance for dummys'), (3, 'Calorie deficit');
ERROR:  el valor nulo en la columna «id» de la relación «courses_category» viola la restricción de no nulo
DETALLE:  La fila que falla contiene (null, 1, CSS Flexbox).
courses_exercise=# INSERT INTO courses_category (id, category, title) VALUES (1, 1, 'CSS Flexbox'), (2, 2, 'Finance for dummys'), (3, 3, 'Calorie deficit');
INSERT 0 3
courses_exercise=# SELECT * FROM users_role;
 id |  name   | role
----+---------+------
  1 | Mario   |    1
  2 | Valeria |    2
  3 | Alex    |    3
(3 filas)


courses_exercise=# INSERT INTO users (name, email, password, age) VALUES (1, 'mario@email.com', 'mario123', 28), (2, 'valeria@email.com', 'valeria123', 24), (3, 'alex@email.com', 'alex123', 27);
INSERT 0 3
courses_exercise=# SELECT * FROM users;
 id | name |       email       |  password  | age
----+------+-------------------+------------+-----
  1 |    1 | mario@email.com   | mario123   |  28
  2 |    2 | valeria@email.com | valeria123 |  24
  3 |    3 | alex@email.com    | alex123    |  27
(3 filas)


courses_exercise=# SELECT * FROM courses_category;
 id | category |       title
----+----------+--------------------
  1 |        1 | CSS Flexbox
  2 |        2 | Finance for dummys
  3 |        3 | Calorie deficit
(3 filas)


courses_exercise=# INSERT INTO courses (title, description, level, teacher) VALUES (1, 'Learn how CSS Flexbox works', 'Medium', 1), (2, 'Learn to save money', 'Beginner', 3), (3, 'Practice new diets', 'Advanced', 2);
INSERT 0 3
courses_exercise=# SELECT * FROM courses;
 id | title |         description         |  level   | teacher
----+-------+-----------------------------+----------+---------
  1 |     1 | Learn how CSS Flexbox works | Medium   |       1
  2 |     2 | Learn to save money         | Beginner |       3
  3 |     3 | Practice new diets          | Advanced |       2
(3 filas)


courses_exercise=# INSERT INTO courses_video (title, url) VALUES (1, 'www.csscourse.com'), (2, 'www.financecontrol.com'), (3, 'www.fitnessdiets.com');
ERROR:  no existe la relación «courses_video»
LÍNEA 1: INSERT INTO courses_video (title, url) VALUES (1, 'www.cssco...
                     ^
courses_exercise=# INSERT INTO course_video (title, url) VALUES (1, 'www.csscourse.com'), (2, 'www.financecontrol.com'), (3, 'www.fitnessdiets.com');
INSERT 0 3
